# Generated by Django 5.0 on 2023-12-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
